### ISSUE TITLE
`panacead export` panics due to IBC

### ISSUE THREAD

**Issue by youngjoon-lee** [medibloc/panacea-core#172]
```bash
$ panacead export

panic: UnmarshalJSON cannot decode empty bytes

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get(0x22c0698, 0xc000f3ea50, 0xc0000111b8, 0x228dc40, 0xc0001196c0, 0x228dc90, 0xc000119780, 0xc0002184f8, 0x3, 0x11, ...)
        /home/oudwud/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.6/x/params/types/subspace.go:109 +0x31c
github.com/cosmos/cosmos-sdk/x/ibc/core/02-client/keeper.Keeper.GetAllowedClients(...)
        /home/oudwud/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.6/x/ibc/core/02-client/keeper/params.go:11
github.com/cosmos/cosmos-sdk/x/ibc/core/02-client/keeper.Keeper.GetParams(0x228dc40, 0xc0001196d0, 0x22c0698, 0xc000f3ea50, 0x22c0698, 0xc000f3ea50, 0xc0000111b8, 0x228dc40, 0xc0001196c0, 0x228dc90, ...)
        /home/oudwud/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.6/x/ibc/core/02-client/keeper/params.go:17 +0x187
github.com/cosmos/cosmos-sdk/x/ibc/core/02-client.ExportGenesis(0x22a9a48, 0xc000124010, 0x22c00a8, 0xc000207580, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, ...)
        /home/oudwud/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.6/x/ibc/core/02-client/genesis.go:66 +0x2f8
github.com/cosmos/cosmos-sdk/x/ibc/core.ExportGenesis(0x22a9a48, 0xc000124010, 0x22c00a8, 0xc000207580, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, ...)
        /home/oudwud/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.6/x/ibc/core/genesis.go:23 +0x98
github.com/cosmos/cosmos-sdk/x/ibc/core.AppModule.ExportGenesis(0xc00000c5a0, 0x20300000000000, 0x22a9a48, 0xc000124010, 0x22c00a8, 0xc000207580, 0x0, 0x0, 0x0, 0x0, ...)
        /home/oudwud/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.6/x/ibc/core/module.go:156 +0xbb
github.com/cosmos/cosmos-sdk/types/module.(*Manager).ExportGenesis(0xc000590cb0, 0x22a9a48, 0xc000124010, 0x22c00a8, 0xc000207580, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
        /home/oudwud/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.6/types/module/module.go:325 +0x135
github.com/medibloc/panacea-core/app.(*App).ExportAppStateAndValidators(0xc000dc0900, 0xc001172800, 0x2f89fe8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/oudwud/repos/panacea-core/app/export.go:33 +0x1e8
github.com/medibloc/panacea-core/cmd/panacead/cmd.appCreator.appExport(0x22b5de8, 0xc00000fae8, 0x22c5d18, 0xc000f3ea50, 0x22bc678, 0xc000ea34c0, 0xc0000111b8, 0x22aa880, 0xc001172840, 0x22c25f0, ...)
        /home/oudwud/repos/panacea-core/cmd/panacead/cmd/root.go:279 +0x34d
github.com/cosmos/cosmos-sdk/server.ExportCmd.func1(0xc000fc5180, 0x2f89fe8, 0x0, 0x0, 0x0, 0x0)
        /home/oudwud/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.6/server/export.go:71 +0x45e
github.com/spf13/cobra.(*Command).execute(0xc000fc5180, 0x2f89fe8, 0x0, 0x0, 0xc000fc5180, 0x2f89fe8)
        /home/oudwud/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000f76780, 0x0, 0x0, 0xc0001559b0)
        /home/oudwud/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/oudwud/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/oudwud/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000f76780, 0xc0001559b0, 0x15, 0x22c5d18, 0xc000f3ea50)
        /home/oudwud/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.6/server/cmd/execute.go:36 +0x265
main.main()
        /home/oudwud/repos/panacea-core/cmd/panacead/main.go:13 +0x45
```

**Comment by youngjoon-lee** [comment]
> If your chain is using IBC, make sure to add IBC initial genesis state to the genesis file. You can use the following command to add IBC initial genesis state to the genesis file.

https://docs.cosmos.network/v0.42/migrations/chain-upgrade-guide-040.html

> Note: This would add IBC state with IBC's send_enabled: false and receive_enabled: false. Make sure to update them to true in the above command if are planning to enable IBC transactions with chain upgrade. Otherwise you can do it via a governance proposal.

**Comment by youngjoon-lee** [comment]
We also need to check about the `x/wasm`.

**Comment by gyuguen** [comment]
I found solution.
`ibc` and `x/wasm` are setting required in `genesis.json`
Accoding to [chain-upgrade-guide-040.](https://docs.cosmos.network/v0.42/migrations/chain-upgrade-guide-040.html) `

Here's what you need to set up the `ibc`.
```bash
cat v40_genesis.json | jq '.app_state |= . + {"ibc":{"client_genesis":{"clients":[],"clients_consensus":[],"create_localhost":false},"connection_genesis":{"connections":[],"client_connection_paths":[]},"channel_genesis":{"channels":[],"acknowledgements":[],"commitments":[],"receipts":[],"send_sequences":[],"recv_sequences":[],"ack_sequences":[]}},"transfer":{"port_id":"transfer","denom_traces":[],"params":{"send_enabled":true,"receive_enabled":true}},"capability":{"index":"1","owners":[]}}' > tmp_genesis.json && mv tmp_genesis.json v40_genesis.json
```

Likewise, It is a necessary setting for `x/wasm`
```bash
cat v40_genesis.json | \
jq -c '.app_state.wasm.codes = []' | \
jq -c '.app_state.wasm.contracts = []' | \
jq -c '.app_state.wasm.gen_msgs = []' | \
jq -c '.app_state.wasm.params.code_upload_access.address = ""' | \
jq -c '.app_state.wasm.params.code_upload_access.permission = "Everybody"' | \
jq -c '.app_state.wasm.params.instantiate_default_permission = "Everybody"' | \
jq -c '.app_state.wasm.params.max_wasm_code_size = "614400"' | \
jq -c '.app_state.wasm.sequences += [{"id_key":"BGxhc3RDb2RlSWQ=","value":"1"},{"id_key":"BGxhc3RDb250cmFjdElk","value":"1"}]' | \
jq > v40_genesis.json
```
