### ISSUE TITLE
Querying AOL records

### ISSUE THREAD

**Issue by jwitos** [medibloc/panacea-core#5]
Hi,

I am wondering if there is a way to verify AOL records by a transaction hash. 
After I add a record to the topic with:

    panaceacli tx aol add-record <topic_owner> <topic_name> <key> <value>

I get the correct response with TxHash assigned to it, e.g.:

    Response:
      TxHash: 4A68ED8224EE8DFABF1E06CE82945E1F054BEC1FC6962192043822261C57CC01

How do I query Panacea to verify the transaction by this hash? I tried it by running 

    panaceacli query tx 4A68ED8224EE8DFABF1E06CE82945E1F054BEC1FC6962192043822261C57CC01

But ended up getting the segmentation error:

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xcbcdf5]

goroutine 1 [running]:
github.com/tendermint/tendermint/lite/proxy.GetCertifiedCommit(0x14802, 0x145dbc0, 0xc000188390, 0x0, 0x0, 0x1, 0x0, 0xc000569dc0, 0xc000569d90)
        /home/x/work/pkg/mod/github.com/tendermint/tendermint@v0.31.9/lite/proxy/query.go:139 +0x105
github.com/cosmos/cosmos-sdk/client/context.CLIContext.Verify(0xc00079e5b0, 0x0, 0x145dbc0, 0xc000188390, 0x0, 0x0, 0x142e5c0, 0xc000132008, 0xf36657, 0x4, ...)
        /home/x/work/pkg/mod/github.com/medibloc/cosmos-sdk@v0.35.3/client/context/query.go:185 +0x66
github.com/cosmos/cosmos-sdk/client/tx.ValidateTxResult(0xc00079e5b0, 0x0, 0x145dbc0, 0xc000188390, 0x0, 0x0, 0x142e5c0, 0xc000132008, 0xf36657, 0x4, ...)
        /home/x/work/pkg/mod/github.com/medibloc/cosmos-sdk@v0.35.3/client/tx/utils.go:86 +0x8e
github.com/cosmos/cosmos-sdk/client/tx.queryTx(0xc00079e5b0, 0xc00079e5b0, 0x0, 0x145dbc0, 0xc000188390, 0x0, 0x0, 0x142e5c0, 0xc000132008, 0xf36657, ...)
        /home/x/work/pkg/mod/github.com/medibloc/cosmos-sdk@v0.35.3/client/tx/utils.go:157 +0x371
github.com/cosmos/cosmos-sdk/client/tx.QueryTxCmd.func1(0xc0001d3900, 0xc00000ea00, 0x1, 0x2, 0x0, 0x0)
        /home/x/work/pkg/mod/github.com/medibloc/cosmos-sdk@v0.35.3/client/tx/query.go:117 +0x10b
github.com/spf13/cobra.(*Command).execute(0xc0001d3900, 0xc00000e9a0, 0x2, 0x2, 0xc0001d3900, 0xc00000e9a0)
        /home/x/work/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001d2780, 0x8a7030, 0xc0001d2780, 0xf356d6)
        /home/x/work/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/x/work/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0001d2780, 0x1303dc8, 0x2, 0xc000572ba0)
        /home/x/work/pkg/mod/github.com/tendermint/tendermint@v0.31.9/libs/cli/setup.go:89 +0x3c
main.main()
        /tmp/panacea-core/cmd/panaceacli/main.go:117 +0x895
```

I know that I can query the AOL itself with `panaceacli query aol get-record`, but that does not allow me to query the transaction by its hash.

Thank you!

**Comment by cl9200** [comment]
There is a bug in the v1.2.4 version of the cli code not initializing the light node verifier.
Please use the tag version v1.2.5. (https://github.com/medibloc/panacea-core/tree/v1.2.5)

Thank you!
