### ISSUE TITLE
Sequence is sometimes not synced with Java SDK

### ISSUE THREAD

**Issue by youngjoon-lee** [medibloc/panacea-core#64]
When Medipass uses the Panacea Testnet, they **sometimes** get an error that the account number and the sequence number is not correct (when verifying the transaction).

This is the log from Medipass server.
```
2020-10-14 11:19:54.324  INFO 1 --- [p-nio-80-exec-7] m.m.blockchain.client.MedipassBcClient2  : [signMedicalRecord] key : me.medipass.dynamo.blockchain.BlockchainDataKey@42664596, hashData : rUa4Ft2RAiVeCz5jiyfh2owun25xEytEuD3B4Ce8skE=, writer : Wallet[addressBytes={-29,83,74,58,-48,-17,-100,-76,-119,73,-18,88,-12,-113,-3,-70,-80,73,64,35},address=panacea1udf55wksa7wtfz2faev0frlah2cyjspracwzkg,ecKey=ECKey{pub HEX=021b886bd441d83fc6e7074896ca8b226e69b2d56ca212cc3647efdb2edaed9713, isEncrypted=false, isPubKeyOnly=false},pubKeyForSign=Pubkey[value=AhuIa9RB2D/G5wdIlsqLIm5pstVsohLMNkfv2y7a7ZcT
],accountNumber=6,sequence=6587,chainId=hygieia-1], fee : Wallet[addressBytes={105,-51,9,-31,-77,-82,-53,-105,-96,-58,-81,11,32,71,-121,-88,-38,115,-83,-74},address=panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu,ecKey=ECKey{pub HEX=03219b48373bb79e7f6e3223a49383bab7222ea03c8f6062cdee40d3ae6b6577fa, isEncrypted=false, isPubKeyOnly=false},pubKeyForSign=Pubkey[value=AyGbSDc7t55/bjIjpJODurciLqA8j2Bize5A065rZXf6
],accountNumber=3,sequence=10922,chainId=hygieia-1]
```

Possibly, it might be an issue of the Java SDK, but let's debug it at the larger scope.

**Comment by youngjoon-lee** [comment]
From [my test code](https://gist.github.com/youngjoon-lee/69c1f54cf87db3fddc78e8401ab5852f), I saw the sequence is not increased even though I create the `Wallet` object and call `ensureWalletIsReady()` every time.

Log
```
account:3, sequence:10951
account:6, sequence:6611
TX SUCCEEDED
account:3, sequence:10951
account:6, sequence:6611

PanaceaApiError[error=broadcast_tx_commit: response error: RPC error -32603 - Internal error: Error on broadcastTxCommit: Tx already exists in cache]
org.medibloc.panacea.PanaceaApiException: PanaceaApiError[error=broadcast_tx_commit: response error: RPC error -32603 - Internal error: Error on broadcastTxCommit: Tx already exists in cache]
	at org.medibloc.panacea.PanaceaApiClientGenerator.executeSync(PanaceaApiClientGenerator.java:66)
	at org.medibloc.panacea.impl.PanaceaApiRestClientImpl.broadcast(PanaceaApiRestClientImpl.java:31)
	at org.medibloc.panacea.DebugTest.debug(DebugTest.java:54)
```

**Comment by youngjoon-lee** [comment]
If I put a 2-sec sleep between transactions (instead of the 1-sec sleep), sequences are updated correctly.
```
account:3, sequence:10959
account:6, sequence:6619
TX SUCCEEDED
account:3, sequence:10960
account:6, sequence:6620
TX SUCCEEDED
```
I guess it's related to the block creation interval `1 sec`. Let me dive deeply.

**Comment by youngjoon-lee** [comment]
I also tested with a simple bash script.
```bash
# check the sequence before the transaction
panaceacli query account panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu
curl localhost:1317/auth/accounts/panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu

# execute a transaction with the 'block' mode
panaceacli tx aol add-record panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu yj key1 data1 --chain-id hygieia-1 --from panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu --fees 1000000umed -b block

# check the sequence after the transaction
panaceacli query account panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu
curl localhost:1317/auth/accounts/panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu
```

I expected that I can see the increased sequence from both `panaceacli` and `curl` after the transaction.
However, only `panaceacli` returned the increased sequence. The `curl` returned the previous sequence.

```
+ panaceacli query account panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu
Account:
  Address:       panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu
  Pubkey:        panaceapub1addwnpepqvsekjph8wmeulmwxg36fyurh2mjyt4q8j8kqckdaeqd8tntv4ml5vfe4zp
  Coins:         9904101799978umed
  AccountNumber: 3
  Sequence:      10981
+ curl localhost:1317/auth/accounts/panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu
{"type":"auth/Account","value":{"address":"panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu","coins":[{"denom":"umed","amount":"9904101799978"}],"public_key":{"type":"tendermint/PubKeySecp256k1","value":"AyGbSDc7t55/bjIjpJODurciLqA8j2Bize5A065rZXf6"},"account_number":"3","sequence":"10981"}}+ panaceacli tx aol add-record panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu yj key1 data1 --chain-id hygieia-1 --from panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu --fees 1000000umed -b block
{"chain_id":"hygieia-1","account_number":"3","sequence":"10981","fee":{"amount":[{"denom":"umed","amount":"1000000"}],"gas":"200000"},"msgs":[{"type":"aol/MsgAddRecord","value":{"topic_name":"yj","key":"a2V5MQ==","value":"ZGF0YTE=","writer_address":"panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu","owner_address":"panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu","fee_payer_address":""}}],"memo":""}

confirm transaction before signing and broadcasting [Y/n]: y
Password to sign with 'aol-test':
Response:
  Height: 28380958
  TxHash: 963AA454A7091684515C4B5F1439E425CD748759BEF58EAFB46AA26D206F8FA4
  Data: 7B2274797065223A22616F6C2F5265734164645265636F7264222C2276616C7565223A7B226F776E65725F61646472657373223A2270616E6163656131643878736E63646E346D3965306778783475396A71337538347264383874646B74687A367075222C22746F7069635F6E616D65223A22796A222C226F6666736574223A223330227D7D
  Raw Log: [{"msg_index":"0","success":true,"log":""}]
  Logs: [{"msg_index":0,"success":true,"log":""}]
  GasWanted: 200000
  GasUsed: 21230
  Tags:
    - action = add_record
+ panaceacli query account panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu
Account:
  Address:       panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu
  Pubkey:        panaceapub1addwnpepqvsekjph8wmeulmwxg36fyurh2mjyt4q8j8kqckdaeqd8tntv4ml5vfe4zp
  Coins:         9904100799978umed
  AccountNumber: 3
  Sequence:      10982
+ curl localhost:1317/auth/accounts/panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu
{"type":"auth/Account","value":{"address":"panacea1d8xsncdn4m9e0gxx4u9jq3u84rd88tdkthz6pu","coins":[{"denom":"umed","amount":"9904101799978"}],"public_key":{"type":"tendermint/PubKeySecp256k1","value":"AyGbSDc7t55/bjIjpJODurciLqA8j2Bize5A065rZXf6"},"account_number":"3","sequence":"10981"}}
```

**Comment by youngjoon-lee** [comment]
posted an issue https://github.com/cosmos/cosmos-sdk/issues/7532

**Comment by youngjoon-lee** [comment]
This issue has been fixed. When I tested it with the `cosmos/cosmos-sdk` v0.37.14, it worked well.
So, it would be resolved after upgrading the `panacea-core` from `v1.2.5-internal` to `v1.3.1` (which is based on the `cosmos/cosmos-sdk@v0.37.14`).

Please see the details: https://github.com/cosmos/cosmos-sdk/issues/7532
